language: R
sudo: true
cache: packages
dist: xenial

after_success:
  - Rscript -e 'library(covr);codecov()'

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
